### ISSUE TITLE
Add github action that detects pull requests that contain mistakes

### ISSUE THREAD

**Issue by jyaif** [pewpewlive/ppl-i18n#135]
Examples of common mistakes:
* Missing "%s"
* Missing quotation marks

Ideally there would be a github action that would automatically detect such mistakes.
Such github action should be written either in python or in golang.

An other useful thing a github action could do is automatically regenerate the README.md.

**Comment by SKPG-Tech** [comment]
Should dots be added to checking too? And or capitalization?

**Comment by jyaif** [comment]
A warning could be issued in those cases, yes, but it shouldn't block a pull request (unlike the errors I mentioned before).

Another thing that could be done is checking that the JSON is correct. Several people (me included) introduced errors while editing it!

**Comment by SKPG-Tech** [comment]
I'm not sure about the JSON checking, but I could try that too.

**Comment by SKPG-Tech** [comment]
> A warning could be issued in those cases

Would that be just a simple warning in the action details and a PR comment to inform about it? (examples below)
![image](https://user-images.githubusercontent.com/42890752/112889679-a2004c00-90de-11eb-8733-37bec7fcdf8e.png)
![image](https://user-images.githubusercontent.com/42890752/112891149-72eada00-90e0-11eb-9815-778653675a06.png)

**Comment by jyaif** [comment]
Yes!

To recap, ideally we want:
1/ Errors for missing "%s", missing quotation marks, invalid JSON.
2/ Warnings for periods at the end, and missing capitalization.
