### ISSUE TITLE
Add language support for Traditional Chinese?

### ISSUE THREAD

**Issue by curiousRay** [pewpewlive/ppl-i18n#157]
Hi, I just found this game on Play Store by chance, and found it fascinating, would u like to add Traditional Chinese language support? I'm very much glad to contribute.

**Comment by jyaif** [comment]
Hi,
We can try to support Traditional Chinese. Can you translate a dozen string so that I can try and see if my character generator works well enough?

**Comment by curiousRay** [comment]
I've translated some in the file attached. Please take a [look.](url)
(Sorry for the late reply)
[cht.zip](https://github.com/jyaif/ppl-i18n/files/6644277/cht.zip)

**Comment by jyaif** [comment]
Thank you!

Does this look readable to you?

![Screenshot from 2021-06-13 23-14-53](https://user-images.githubusercontent.com/251239/121822043-2fdee280-cc9d-11eb-9e9e-da79ba43ac74.png)
![Screenshot from 2021-06-13 23-12-54](https://user-images.githubusercontent.com/251239/121822003-e55d6600-cc9c-11eb-84a3-8aa59f6d572a.png)
![CHT](https://user-images.githubusercontent.com/251239/121821983-cc54b500-cc9c-11eb-985a-97ad9e07bfe4.png)

**Comment by curiousRay** [comment]
It seems that tofu can be seen clearly in the interface. I use utf-8 encoding in my translation file.
And the padding is a little narrow.
Is it possible to consider using noto fonts?

![Untitled](https://user-images.githubusercontent.com/24775856/121835930-035eb100-cd05-11eb-974d-e81e39742a52.png)

**Comment by jyaif** [comment]
I will fix the missing characters and the padding problem (which is due to the missing characters).

> Is it possible to consider using noto fonts?
PewPew Live uses its own font rendering system, but I do use a noto font to genereate the CJK characters. The problem with the missing characters is because the automatic generation of CJK characters is still a little bit buggy.

**Comment by SKPG-Tech** [comment]
Closing as a stale issue, reopen when necessary!
