### ISSUE TITLE
Add language support for Simplified Chinese

### ISSUE THREAD

**Issue by KnightK22** [pewpewlive/ppl-i18n#248]
Hello! Im a fan of Pewpew series and I've played Pewpew2 over 3 years. It's really an improtant game in my life. Today I found this game in Play store by chance, would u add Simplified Chinese support? I'll do my best to help u.

**Comment by jyaif** [comment]
Yes, lets try and support Simplified Chinese :-)

**Comment by jyaif** [comment]
You can fill out https://github.com/jyaif/ppl-i18n/blob/master/translations/chs.po

**Comment by KnightK22** [comment]
Thanks a lot! I'll do my best to complete it!

**Comment by jyaif** [comment]
Thanks to @huanbin-li, simplified Chinese will be in the next update of the game!
