### ISSUE TITLE
Adding support for Hindi

### ISSUE THREAD

**Issue by arjunindia** [pewpewlive/ppl-i18n#264]
I'm opening this issue to look at the possibility of adding Hindi. 
Current complications include rendering letters with lots of curved parts and supporting ligatures. Also the words can be larger.

https://docs.microsoft.com/en-us/typography/script-development/devanagari

**Comment by arjunindia** [comment]
![kblhi2(2)_1.jpg](https://user-images.githubusercontent.com/37960163/184520205-b26fda0b-c19f-49d9-9150-c65e7aec3a7b.jpg)

![kblhi2(2)_2.jpg](https://user-images.githubusercontent.com/37960163/184520208-006bad62-039d-4df6-ad66-a8f0ce3818e6.jpg)

![kblhi2(2)_3.jpg](https://user-images.githubusercontent.com/37960163/184520211-6e9918d2-4bb7-4fda-8f66-b81609328cce.jpg)

**Comment by jyaif** [comment]
Thanks for the information; I wanted to know more about hindi for a long time.

It's now clear to me that unfortunately PPL can't support Hindi without a profound change in how the text is rendered. I'm not saying it will never happen, but many other features in PPL have a higher priority.
