### ISSUE TITLE
How to apply 100% completed Chinese translation in iOS version?

### ISSUE THREAD

**Issue by haolloyin** [pewpewlive/ppl-i18n#271]
Hi dev, since the Chinese translation is 100% complete, how can I apply it to the game? Thanks!

> [Simplified Chinese](https://github.com/pewpewlive/ppl-i18n/blob/master/translations/chs.po) (100% complete! 🎉)

**Comment by SKPG-Tech** [comment]
Hi! Check your app store for updates, the latest update should contain Chinese in the languages settings.

**Comment by haolloyin** [comment]
> Hi! Check your app store for updates, the latest update should contain Chinese in the languages settings.

Hi @SKPG-Tech, the screenshots below show my PPL version, and Language Settings, which doesn't seem to have a Chinese language option.

![image](https://user-images.githubusercontent.com/1009628/186625437-6afe4be9-ad71-438b-b1b9-e2fe40937d87.png)

![image](https://user-images.githubusercontent.com/1009628/186625493-4b78a1d8-6563-4409-8408-c1879bf84f60.png)


It seems that no new version of PPL has been released recently (the App Store page doesn't show `What's New`, but PP does).

PPL: https://apps.apple.com/us/app/pewpew-live/id1556977519
![image](https://user-images.githubusercontent.com/1009628/186625274-11499307-6f73-460f-9beb-91a7b888e27e.png)

PP: https://apps.apple.com/us/app/pewpew/id314964252
![image](https://user-images.githubusercontent.com/1009628/186624695-42b5bc65-ce6d-4c88-bf5d-bd8bc93a49b4.png)

Thanks.

**Comment by jyaif** [comment]
The iOS version of PPL has not yet been updated. I'm working on it, but it takes time.

**Comment by haolloyin** [comment]
> The iOS version of PPL has not yet been updated. I'm working on it, but it takes time.

Oh, I see, thanks.

**Comment by SKPG-Tech** [comment]
Closing this issue for now, we'll comment again once the update is out.
