### ISSUE TITLE
Pls add arabic

### ISSUE THREAD

**Issue by MounirXD7** [pewpewlive/ppl-i18n#273]
Can you add the arabic language?i can translate the whole game(cuz my language is arabic so...)

**Comment by SKPG-Tech** [comment]
Hi, Arabic is one of the languages PewPew Live will probably not support for a while. 

The language has many complex curves and requires us to rework the whole text rendering system to allow ligatures. 
At some point we might implement the support, but currently, the game has other higher priority features to add.

Sorry for the inconvenience.

**Comment by MounirXD7** [comment]
Thx for replying
BUT if you need a help about *arabic things like translation*just talk to me bro

**Comment by SKPG-Tech** [comment]
Sure, we'll be sure to ask you for help when we eventually decide to implement Arabic.

For now, I'm closing this issue. We will reopen once help is needed.
