### ISSUE TITLE
Show the flag as an emoji before the country name

### ISSUE THREAD

**Issue by jyaif** [pewpewlive/ppl-i18n#334]
In the list of languages, it would be nice to show a flag associated with the language before the language name:
![image](https://github.com/pewpewlive/ppl-i18n/assets/251239/4265cb46-7479-4a19-97fc-4438ad30ad51)

This would be done by adding an "emoji" field to every language in `metadata.json`, and using that field to generate `README.md`.

**Comment by SKPG-Tech** [comment]
Implemented in https://github.com/pewpewlive/ppl-i18n/commit/80cf9d4823361bbeb5bd4ed9a942d6d3ab7dfa6e
