### ISSUE TITLE
Uzbek pew pew live translate

### ISSUE THREAD

**Issue by Qudratillayev** [pewpewlive/ppl-i18n#343]
Hi. I want to add an Uzbek translation to Pew pew Live.

**Comment by Qudratillayev** [comment]
I have everything ready. I have finished translating the game into Uzbek.

**Comment by Qudratillayev** [comment]
Since the Uzbek language is based on the Latin alphabet, it is not necessary to create a font for it.

**Comment by Tasty-Kiwi** [comment]
Sorry for the fact that the github action is a bit broken right now, but the developer has agreed to add Uzbek to the game. Thanks for translating :)

**Comment by Qudratillayev** [comment]
In the Uzbek language, the word "Uzbek" is called "O'zbek". And my nickname: "Ali2008uzb". In blue.
And sorry for the late reply.

**Comment by SKPG-Tech** [comment]
Great, thanks! I added you to the credits, now I will give you a badge, I'm just not sure if this is your account, just to confirm, is this it?
![image](https://github.com/pewpewlive/ppl-i18n/assets/42890752/4732e367-ce84-41ac-9eba-044861928275)

**Comment by Qudratillayev** [comment]
Yes, It's my account.

**Comment by SKPG-Tech** [comment]
Badge added!
