### ISSUE TITLE
I am interested in contributing in the Spanish language

### ISSUE THREAD

**Issue by S0UKXZ** [pewpewlive/ppl-i18n#441]
Hello, I am interested in contributing in the Spanish language of ppl2. In case you have any doubts, I am a native speaker and I would like to contribute, thank you.

**Comment by SKPG-Tech** [comment]
Hello! 

So far, the Spanish translation is missing some strings, it would be greatly appreciated if you translated those.
If you find other translations that can be improved, feel free to do so!
If you have questions, please join the Discord server, where I'll answer them. 

Thank you! 

Go ahead and get started by forking and editing this file: https://github.com/pewpewlive/ppl-i18n/blob/master/translations/spa.po
